### ISSUE TITLE
Easier catalog download

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-catalogs#1]
Is the current method of obtaining catalogs via github too onerous? Should we have download links directly from the USGS website?

**Comment by cmueller-usgs** [comment]
Peter,

I've kind of been feeling that a direct link from the website might be
easier. I would also be willing to help rethink that matrix that shows
what's included in the various catalogs.

Chuck


--------------------------------------------------------
Charles S. Mueller
U.S. Geological Survey
cmueller@usgs.gov,  tel: 303-273-8559,  fax: 303-273-8600
Mail/Post:   USGS-MS966    Box 25046 DFC    Denver, CO 80225 USA
FedEx,UPS,etc:   USGS-Rm428    1711 Illinois St.    Golden, CO 80401 USA
--------------------------------------------------------

**Comment by pmpowers-usgs** [comment]
The filenames in the explanatory tables have been updated to be direct links to the raw catalogs. I think this will suffice for now.
