### ISSUE TITLE
projected coordinate system

### ISSUE THREAD

**Issue by 717524640** [usgs/nshmp-haz-catalogs#2]
Which projected coordinate system should I choose to plot the data in ArcGIS? Thanks.

**Comment by pmpowers-usgs** [comment]
How you choose to project data is your decision. The catalogs are registered to the WGS-84 reference system and there is no prescribed way to project them. I don't even think you have to for a lot of ArcGIS maps, or you just use the reference coordinate system as the projected coordinate system.
